'''
Rename files generated by salmon from quant.sf to SRR id present in the path
Make sure the destination folder exists
'''
import sys
from subprocess import call
from shutil import copyfile
#read paths
with open(sys.argv[1],'r') as f:
	paths=f.read().splitlines()
#print paths
#t2=f.split('_map')[0].rsplit('/')[-1]
for p in paths:
	#./SRR_LISTbc_out/SRR2735893_map/quant.sf
	#./rm_out/rm_af1aa_out/SRR764782_map/quant.sf
	t=p.split('_map')[0].rsplit('/')[-1]
	#print t
	#copy file p to t
	dst="./quant_files_named/"+t	
	copyfile(p, dst)

